<?php

namespace ContainerRbLB6pX;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_OByFBYService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator._OByFBY' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator._OByFBY'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'App\\Controller\\SecurityController::loginAction' => ['privates', '.service_locator.zFcJjKU', 'get_ServiceLocator_ZFcJjKUService', true],
            'App\\Controller\\TaskController::createAction' => ['privates', '.service_locator.tgVVt0z', 'get_ServiceLocator_TgVVt0zService', true],
            'App\\Controller\\TaskController::deleteTaskAction' => ['privates', '.service_locator.Vuxczi7', 'get_ServiceLocator_Vuxczi7Service', true],
            'App\\Controller\\TaskController::editAction' => ['privates', '.service_locator.Vuxczi7', 'get_ServiceLocator_Vuxczi7Service', true],
            'App\\Controller\\TaskController::listAction' => ['privates', '.service_locator.ofZU1r4', 'get_ServiceLocator_OfZU1r4Service', true],
            'App\\Controller\\TaskController::listTasksDone' => ['privates', '.service_locator.ofZU1r4', 'get_ServiceLocator_OfZU1r4Service', true],
            'App\\Controller\\TaskController::toggleTaskAction' => ['privates', '.service_locator.Vuxczi7', 'get_ServiceLocator_Vuxczi7Service', true],
            'App\\Controller\\UserController::createAction' => ['privates', '.service_locator.j_IwPQv', 'get_ServiceLocator_JIwPQvService', true],
            'App\\Controller\\UserController::editAction' => ['privates', '.service_locator.6RWgksL', 'get_ServiceLocator_6RWgksLService', true],
            'App\\Controller\\UserController::listAction' => ['privates', '.service_locator.Lf9.KfB', 'get_ServiceLocator_Lf9_KfBService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'App\\Kernel::terminate' => ['privates', '.service_locator.bRdave9', 'get_ServiceLocator_BRdave9Service', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel::terminate' => ['privates', '.service_locator.bRdave9', 'get_ServiceLocator_BRdave9Service', true],
            'App\\Controller\\SecurityController:loginAction' => ['privates', '.service_locator.zFcJjKU', 'get_ServiceLocator_ZFcJjKUService', true],
            'App\\Controller\\TaskController:createAction' => ['privates', '.service_locator.tgVVt0z', 'get_ServiceLocator_TgVVt0zService', true],
            'App\\Controller\\TaskController:deleteTaskAction' => ['privates', '.service_locator.Vuxczi7', 'get_ServiceLocator_Vuxczi7Service', true],
            'App\\Controller\\TaskController:editAction' => ['privates', '.service_locator.Vuxczi7', 'get_ServiceLocator_Vuxczi7Service', true],
            'App\\Controller\\TaskController:listAction' => ['privates', '.service_locator.ofZU1r4', 'get_ServiceLocator_OfZU1r4Service', true],
            'App\\Controller\\TaskController:listTasksDone' => ['privates', '.service_locator.ofZU1r4', 'get_ServiceLocator_OfZU1r4Service', true],
            'App\\Controller\\TaskController:toggleTaskAction' => ['privates', '.service_locator.Vuxczi7', 'get_ServiceLocator_Vuxczi7Service', true],
            'App\\Controller\\UserController:createAction' => ['privates', '.service_locator.j_IwPQv', 'get_ServiceLocator_JIwPQvService', true],
            'App\\Controller\\UserController:editAction' => ['privates', '.service_locator.6RWgksL', 'get_ServiceLocator_6RWgksLService', true],
            'App\\Controller\\UserController:listAction' => ['privates', '.service_locator.Lf9.KfB', 'get_ServiceLocator_Lf9_KfBService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel:terminate' => ['privates', '.service_locator.bRdave9', 'get_ServiceLocator_BRdave9Service', true],
        ], [
            'App\\Controller\\SecurityController::loginAction' => '?',
            'App\\Controller\\TaskController::createAction' => '?',
            'App\\Controller\\TaskController::deleteTaskAction' => '?',
            'App\\Controller\\TaskController::editAction' => '?',
            'App\\Controller\\TaskController::listAction' => '?',
            'App\\Controller\\TaskController::listTasksDone' => '?',
            'App\\Controller\\TaskController::toggleTaskAction' => '?',
            'App\\Controller\\UserController::createAction' => '?',
            'App\\Controller\\UserController::editAction' => '?',
            'App\\Controller\\UserController::listAction' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::terminate' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'kernel::terminate' => '?',
            'App\\Controller\\SecurityController:loginAction' => '?',
            'App\\Controller\\TaskController:createAction' => '?',
            'App\\Controller\\TaskController:deleteTaskAction' => '?',
            'App\\Controller\\TaskController:editAction' => '?',
            'App\\Controller\\TaskController:listAction' => '?',
            'App\\Controller\\TaskController:listTasksDone' => '?',
            'App\\Controller\\TaskController:toggleTaskAction' => '?',
            'App\\Controller\\UserController:createAction' => '?',
            'App\\Controller\\UserController:editAction' => '?',
            'App\\Controller\\UserController:listAction' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:terminate' => '?',
        ]);
    }
}
