<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerLuj2wSi\App_KernelTestDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerLuj2wSi/App_KernelTestDebugContainer.php') {
    touch(__DIR__.'/ContainerLuj2wSi.legacy');

    return;
}

if (!\class_exists(App_KernelTestDebugContainer::class, false)) {
    \class_alias(\ContainerLuj2wSi\App_KernelTestDebugContainer::class, App_KernelTestDebugContainer::class, false);
}

return new \ContainerLuj2wSi\App_KernelTestDebugContainer([
    'container.build_hash' => 'Luj2wSi',
    'container.build_id' => 'd4c49439',
    'container.build_time' => 1666445270,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerLuj2wSi');
