<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXSH9LYu\App_KernelTestDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXSH9LYu/App_KernelTestDebugContainer.php') {
    touch(__DIR__.'/ContainerXSH9LYu.legacy');

    return;
}

if (!\class_exists(App_KernelTestDebugContainer::class, false)) {
    \class_alias(\ContainerXSH9LYu\App_KernelTestDebugContainer::class, App_KernelTestDebugContainer::class, false);
}

return new \ContainerXSH9LYu\App_KernelTestDebugContainer([
    'container.build_hash' => 'XSH9LYu',
    'container.build_id' => '21b6b42f',
    'container.build_time' => 1665940195,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXSH9LYu');
