<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerH1NmExV\App_KernelTestDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerH1NmExV/App_KernelTestDebugContainer.php') {
    touch(__DIR__.'/ContainerH1NmExV.legacy');

    return;
}

if (!\class_exists(App_KernelTestDebugContainer::class, false)) {
    \class_alias(\ContainerH1NmExV\App_KernelTestDebugContainer::class, App_KernelTestDebugContainer::class, false);
}

return new \ContainerH1NmExV\App_KernelTestDebugContainer([
    'container.build_hash' => 'H1NmExV',
    'container.build_id' => 'edcec708',
    'container.build_time' => 1666680396,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerH1NmExV');
