<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXrZzNgb\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXrZzNgb/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerXrZzNgb.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerXrZzNgb\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerXrZzNgb\App_KernelDevDebugContainer([
    'container.build_hash' => 'XrZzNgb',
    'container.build_id' => '4ce7c2d5',
    'container.build_time' => 1666444534,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXrZzNgb');
