<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerClzoNUt\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerClzoNUt/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerClzoNUt.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerClzoNUt\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerClzoNUt\App_KernelDevDebugContainer([
    'container.build_hash' => 'ClzoNUt',
    'container.build_id' => 'e7fb03f4',
    'container.build_time' => 1664736061,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerClzoNUt');
