<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerRbLB6pX\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerRbLB6pX/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerRbLB6pX.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerRbLB6pX\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerRbLB6pX\App_KernelDevDebugContainer([
    'container.build_hash' => 'RbLB6pX',
    'container.build_id' => 'f3ba5eb5',
    'container.build_time' => 1666676637,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerRbLB6pX');
